name: travelapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  supabase_flutter: ^2.5.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  http: ^1.2.1
  geolocator: ^14.0.2
  flutter_sound: ^9.3.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  video_player: ^2.8.6
  google_sign_in: ^6.2.1 # Added for Google Login
  flutter_dotenv: ^5.1.0 # Added for secure API key management
  geocoding: ^4.0.0
  exif: ^3.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/google.png
    - assets/background.mp4
    - assets/background2.mp4