import 'package:hive/hive.dart';

part 'journal_entry.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0)
class JournalEntry extends HiveObject {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String title;
  @HiveField(2)
  final String description;
  @HiveField(3)
  List<String> photoPaths;
  @HiveField(4)
  final String date;
  @HiveField(5)
  final String location;
  @HiveField(6)
  List<String> tags;
  @HiveField(7)
  bool isSynced;
  @HiveField(8)
  final double latitude;
  @HiveField(9)
  final double longitude;
  @HiveField(10)
  String voiceNotePath;
  @HiveField(11)
  String transcription;

  // Added a field to mark for deletion when offline
  @HiveField(12)
  bool markedForDeletion;

  JournalEntry({
    required this.id,
    required this.title,
    required this.description,
    required this.photoPaths,
    required this.date,
    required this.location,
    required this.tags,
    this.isSynced = false,
    required this.latitude,
    required this.longitude,
    required this.voiceNotePath,
    required this.transcription,
    this.markedForDeletion = false,
  });
}